version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout

      - restore_cache:
          name: BE/Restore Yarn Package Cache
          keys:
            - be-yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: BE/Install Dependencies
          command: yarn install
      - save_cache:
          name: BE/Save Yarn Package Cache
          key: be-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/be
      - run:
          name: BE/Build Typescript
          command: yarn build:be

      - restore_cache:
          name: FE/Restore Yarn Package Cache
          keys:
            - fe-yarn-packages-{{ checksum "fe/yarn.lock" }}
      - run:
          name: FE/Install Dependencies
          command: cd fe && yarn install
      - save_cache:
          name: FE/Save Yarn Package Cache
          key: fe-yarn-packages-{{ checksum "fe/yarn.lock" }}
          paths:
            - ~/.cache/yarn/fe
      - run:
          name: FE/Build For React
          command: yarn build:fe

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
