version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          name: BE/Restore Yarn Package Cache
          keys:
            - be-yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: BE/Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: BE/Save Yarn Package Cache
          key: be-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/be

      - restore_cache:
          name: FE/Restore Yarn Package Cache
          keys:
            - fe-yarn-packages-{{ checksum "fe/yarn.lock" }}
      - run:
          name: FE/Install Dependencies
          command: cd fe && yarn install --frozen-lockfile
      - save_cache:
          name: FE/Save Yarn Package Cache
          key: fe-yarn-packages-{{ checksum "fe/yarn.lock" }}
          paths:
            - ~/.cache/yarn/fe
      - run:
          name: FE/Build For React
          command: cd fe && yarn build
